const colors = {
  light: {
    text: '#1A1A2E',
    tint: '#FF6B35',
    background: '#FFF8F0',
    foreground: '#1A1A2E',
    card: '#FFFFFF',
    cardForeground: '#1A1A2E',
    primary: '#FF6B35',
    primaryForeground: '#FFFFFF',
    secondary: '#4ECDC4',
    secondaryForeground: '#FFFFFF',
    muted: '#F5EEE6',
    mutedForeground: '#8A7E74',
    accent: '#FFE66D',
    accentForeground: '#1A1A2E',
    destructive: '#FF6B6B',
    destructiveForeground: '#FFFFFF',
    border: '#F0E8DC',
    input: '#F0E8DC',
    success: '#6BCB77',
    successForeground: '#FFFFFF',
    purple: '#9B5DE5',
    pink: '#FF4D9E',
    blue: '#00BBF9',
    yellow: '#FFD700',
    gold: '#FFD700',
    teal: '#4ECDC4',
    orange: '#FF8B42',
  },
  radius: 24,
};

export default colors;
