uploads = []
outputs = []

[[generated]]
id = "Cp9huOldJAIguZkNm4GMe"
uri = "file://artifacts/arabi-kids/assets/images/icon.png"
type = "image"
title = "arabi kids mascot icon"

[[generated]]
id = "O0PZ1xPS2m6HagSYCpEYt"
uri = "file://artifacts/arabi-kids/assets/images/animals_thumb.png"
type = "image"
title = "animals theme thumbnail"

[[generated]]
id = "FgTlxlPcrsGVy2yDnoRRF"
uri = "file://artifacts/arabi-kids/assets/images/food_thumb.png"
type = "image"
title = "food theme thumbnail"

[[generated]]
id = "xS0jkC0TC643FNvt-49qH"
uri = "file://artifacts/arabi-kids/assets/images/theme_colors.png"
type = "image"
title = "colors theme"

[[generated]]
id = "gwB1dNoKu2Cm9yFhyFudB"
uri = "file://artifacts/arabi-kids/assets/images/theme_numbers.png"
type = "image"
title = "numbers theme"

[[generated]]
id = "RZfg8vrkoNK078tOWLCyl"
uri = "file://artifacts/arabi-kids/assets/images/theme_home.png"
type = "image"
title = "home theme"

[[generated]]
id = "y_ThnbgIIumB5M_SHtWQ5"
uri = "file://artifacts/arabi-kids/assets/images/theme_body.png"
type = "image"
title = "body theme"

[[generated]]
id = "S0WCwA55x6oeUkZnVNOz_"
uri = "file://artifacts/arabi-kids/assets/images/theme_nature.png"
type = "image"
title = "nature theme"

[[generated]]
id = "VRLcyRzfAQ4ZG3yEfMcBg"
uri = "file://artifacts/arabi-kids/assets/images/theme_clothes.png"
type = "image"
title = "clothes theme"
